FROM quay.io/pypa/manylinux_2_28_x86_64


ARG ROCM_VERSION
ARG THEROCK_PATH
ENV GPU_DEVICE_TARGETS="gfx906 gfx908 gfx90a gfx9-4-generic gfx10-3-generic gfx11-generic gfx12-generic"

# Install patchelf and headers for numactl
RUN --mount=type=cache,target=/var/cache/dnf \
    dnf install -y patchelf numactl-devel vim-common

# Install ROCm
RUN --mount=type=cache,target=/var/cache/dnf \
    --mount=type=bind,source=./tools/get_rocm.py,target=get_rocm.py \
    python3 get_rocm.py --rocm-version=$ROCM_VERSION --therock-path=$THEROCK_PATH
ENV PATH="$PATH:/opt/rocm/bin:/opt/rocm/llvm/bin"
RUN printf '%s\n' > /opt/rocm/bin/target.lst ${GPU_DEVICE_TARGETS}

# Install LLVM 18 and dependencies.
RUN --mount=type=cache,target=/var/cache/dnf \
    dnf install -y wget && dnf clean all
RUN mkdir /tmp/llvm-project && wget -qO - https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-18.1.8.tar.gz | tar -xz -C /tmp/llvm-project --strip-components 1 && \
    mkdir /tmp/llvm-project/build && cd /tmp/llvm-project/build && cmake -DLLVM_ENABLE_PROJECTS='clang;lld' -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/lib/llvm-18/ ../llvm && \
    make -j$(nproc) && make -j$(nproc) install && rm -rf /tmp/llvm-project

# Copy in our clang configuiration file
COPY ./docker/manylinux/clang.cfg /usr/lib/llvm-18/bin/clang++.cfg
COPY ./docker/manylinux/clang.cfg /usr/lib/llvm-18/bin/clang.cfg
COPY ./docker/manylinux/clang.cfg /opt/rocm/llvm/bin/clang++.cfg
COPY ./docker/manylinux/clang.cfg /opt/rocm/llvm/bin/clang.cfg

# Install AWS CLI v2
RUN --mount=type=cache,target=/var/cache/dnf \
    dnf install -y curl unzip && \
    curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip && \
    unzip -q /tmp/awscliv2.zip -d /tmp && \
    /tmp/aws/install && \
    rm -rf /tmp/aws /tmp/awscliv2.zip && \
    dnf clean all

