FROM ubuntu:24.04

ENV ROCM_VERSION="7.2.0"
ENV ROCM_BUILD_JOB="compute-rocm-dkms-no-npi-hipclang"
ENV ROCM_BUILD_NUM="16849"
ENV GPU_DEVICE_TARGETS="gfx906 gfx908 gfx90a gfx942 gfx950 gfx1030 gfx1100 gfx1101 gfx1200 gfx1201"

# Install dev and build tools
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install \
      -y --no-install-recommends \
      build-essential \
      ca-certificates \
      clang-18        \
      curl            \
      git             \
      make            \
      patchelf        \
      lsb-release     \
      shellcheck      \
      vim             \
      wget            \
      yamllint        \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install ROCm
RUN --mount=type=cache,target=/var/cache/dnf \
    --mount=type=bind,source=./get_rocm.py,target=get_rocm.py \
    python3 get_rocm.py --rocm-version=$ROCM_VERSION --job-name=$ROCM_BUILD_JOB --build-num=$ROCM_BUILD_NUM
ENV PATH="$PATH:/opt/rocm/bin:/opt/rocm/llvm/bin"
RUN printf '%s\n' > /opt/rocm/bin/target.lst ${GPU_DEVICE_TARGETS}

