name: Build docker

on:
  workflow_call:
    inputs:
      rocm-version:
        required: true
        type: string
      rocm-build-job:
        required: false
        type: string
      rocm-build-num:
        required: false
        type: string
      runner-label:
        required: false
        type: string
        default: "mi-250"
      artifact-prefix:
        required: false
        default: 'plugin_wheels'
        type: string

jobs:
  build-docker:
    runs-on: ${{ inputs.runner-label }}
    steps:
      - name: Clean up old runs
        run: |
          ls
          # Make sure that we own all of the files so that we have permissions to delete them
          docker run --rm -v "./:/rocm-jax" ubuntu /bin/bash -c "chown -R $UID /rocm-jax/* || true"
          # Remove any old work directories from this machine
          rm -rf * || true
          ls
      - name: Print system info
        run: |
          whoami
          printenv
          df -h
          rocm-smi -a || true
          rocminfo | grep gfx || true
      - uses: actions/checkout@v4
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-prefix }}_r${{ inputs.rocm-version }}
          path: ./wheelhouse
      - name: Build JAX docker image
        run: |
          python3 build/ci_build \
            --rocm-version="${{ inputs.rocm-version }}" \
            --rocm-build-job="${{ inputs.rocm-build-job }}" \
            --rocm-build-num="${{ inputs.rocm-build-num }}" \
            build_dockers
      - name: Authenticate to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
            | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push docker images
        env:
          ROCM_VERSION: ${{ inputs.rocm-version }}
        run: |
          ubu22_img="ghcr.io/rocm/jax-ubu22.rocm${ROCM_VERSION//.}:${GITHUB_SHA}"
          ubu24_img="ghcr.io/rocm/jax-ubu24.rocm${ROCM_VERSION//.}:${GITHUB_SHA}"
          echo "Ubuntu 22 image name: ${ubu22_img}"
          echo "Ubuntu 24 image name: ${ubu24_img}"
          docker tag "jax-ubu22.rocm${ROCM_VERSION//.}" "${ubu22_img}"
          docker tag "jax-ubu24.rocm${ROCM_VERSION//.}" "${ubu24_img}"
          docker push "${ubu22_img}"
          docker push "${ubu24_img}"

