name: Lint

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files: **/*.py
      - name: Run black
        uses: psf/black@stable
        with:
          options: '--check --verbose'
          src: ${{ steps.changed-files.outputs.all_changed_files }}
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files: **/*.sh
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: ${{ steps.changed-files.outputs.all_changed_files }}

