name: Jax CI Test Results to DB

on:
  schedule:
    - cron: "10 * * * *"
  workflow_dispatch:
    inputs:
      source-repo:
        description: "ORG/REPO"
        required: false
        default: "ROCm/jax"
        type: string
      source-github-run-id:
        description: "Repo GitHub Run ID"
        required: false
        default: ""
        type: string
    secrets:
      ROCM_JAX_DB_HOSTNAME:
        required: true
      ROCM_JAX_DB_USERNAME:
        required: true
      ROCM_JAX_DB_PASSWORD:
        required: true
      ROCM_JAX_DB_NAME:
        required: true

concurrency:
  group: jax-ci-test-results-to-db
  cancel-in-progress: false

jobs:
  process-test-results:
    runs-on: mysqldb
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install mysql-connector-python
      - name: Upload logs to MySQL database
        env:
          ROCM_JAX_DB_HOSTNAME: ${{ secrets.ROCM_JAX_DB_HOSTNAME }}
          ROCM_JAX_DB_USERNAME: ${{ secrets.ROCM_JAX_DB_USERNAME }}
          ROCM_JAX_DB_PASSWORD: ${{ secrets.ROCM_JAX_DB_PASSWORD }}
          ROCM_JAX_DB_NAME: ${{ secrets.ROCM_JAX_DB_NAME }}
          BUCKET: ${{ secrets.AMD_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AMD_S3_BUCKET_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AMD_S3_BUCKET_SECRET_KEY }}
          FILTER_REPO: ${{ inputs.source-repo }}
          FILTER_RUN_ID: ${{ inputs.source-github-run-id }}
          INPUT_GPU_ARCH: "MI350"
        run: |
          source venv/bin/activate
          ./ci/ingest_jax_ci_logs.sh

