name: Upstream CI Watcher

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  upstream-ci-watcher:
    runs-on: ubuntu-latest
    steps:
      - name: Run watcher script
        run: | 
          ci/upstream_ci_watcher.py --teams-url ${{ secrets.MS_TEAMS_WEBHOOK_URL }} --gh-token ${{ secrets.GITHUB_TOKEN }}

